import Head from 'next/head'
import MainPageBannerComponent from "../components/main-page-banner.component";
import ItemsCarousel from "../components/items-carousel";
import styled from "styled-components";
import Image from "next/image";
import ItemsByCollectionComponent from "../components/items-by-collection.component";
import EmailInputComponent from "../components/email-input.component";
import ItemsByStyleComponent from "../components/items-by-style.component";

const MainPageContainer = styled.div`
  width: 100vw;
  display: flex;
  flex-direction: column;
`

const BannerText = styled.div`
  width: 100vw;
  background-color: rgb(247,247,247);
  height: 20vh;
  margin-top: 10px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const ImageContainer = styled.div`
  height: 30vh;
  width: 100vw;
  background-size: contain;
  background-position: center;
  position: relative;
  margin-top: 35px;
`

const SubscribeContainer = styled.div`
  width: 100vw;
  background-color: rgb(247,247,247);
  height: fit-content;
  padding: 20px;
  margin-top: 10px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
          <MainPageContainer>
            <MainPageBannerComponent></MainPageBannerComponent>
            <ItemsCarousel title={"Trending now"}/>
            <BannerText>
                <h1>
                    Join our mission to save and protect our buzzy pollinators around the globe❤️
                </h1>
                <p>
                    Wear your lovely Bee Kind accessories as a reminder of being part of the community. Every purchase saves the bees.
                </p>
            </BannerText>
            <ItemsCarousel title={"New Arrivals"}/>
            <ImageContainer>
                <Image src="https://cdn.shopify.com/s/files/1/0457/5648/1703/files/BEE-ing_Kind_is_a_Lifestyle_2048x.jpg?v=1623903758"
                            alt="banner-image" layout={"fill"} objectFit="cover"/>
            </ImageContainer>
            <ItemsByCollectionComponent/>
            <SubscribeContainer>
                <EmailInputComponent/>
            </SubscribeContainer>
            <ItemsByStyleComponent/>
              <ImageContainer>
                  <Image src="https://cdn.shopify.com/s/files/1/0457/5648/1703/files/Join_the_Movement_to_Save_Our_Buzzing_Friends_39a722de-5768-4689-84f6-6393f7c5088d_1728x.jpg?v=1623903777"
                         alt="banner-image" layout={"fill"} objectFit="cover"/>
              </ImageContainer>
          </MainPageContainer>
      </main>

      <footer >

      </footer>
    </div>
  )
}
