import Head from 'next/head'
import MainPageBannerComponent from "../components/main-page-banner.component";
import ItemsCarouselComponent from "../components/items-carousel.component";
import styled from "styled-components";
import Image from "next/legacy/image";
import EmailInputComponent from "../components/email-input.component";
import React from "react";
import {gql} from "@apollo/client";
import apolloClient from "../lib/apollo";
import prisma from "../lib/prisma";
import {productData, collectionData} from "../data/data";
import ItemsByCollectionOrStyleComponent from "../components/items-by-collection-or-style.component";
import CartComponent from "../components/cart.component";

const MainPageContainer = styled.div`
  width: 100vw;
  display: flex;
  flex-direction: column;
`

const BannerText = styled.div`
  width: 100vw;
  background-color: rgb(247,247,247);
  height: 20vh;
  margin-top: 10px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

const ImageContainer = styled.div`
  height: 30vh;
  width: 100vw;
  background-size: contain;
  background-position: center;
  position: relative;
  margin-top: 35px;
`

const SubscribeContainer = styled.div`
  width: 100vw;
  background-color: rgb(247,247,247);
  height: fit-content;
  padding: 20px;
  margin-top: 10px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`

export async function getServerSideProps() {
  const productsByIdsQuery = gql`
    query ($id: [Int]!){
      ProductsByMultipleIds(id: $id) {
        productId
        itemName
        rating
        price
        discountedPrice
        frontImageUrl
        isAvailable
      }
    }
  `;

  const dataOne = await apolloClient.query({
    query: productsByIdsQuery,
    variables: {
      id: [1, 2, 3, 4]
    }
  }).then((data) => data.data.ProductsByMultipleIds);

  const dataTwo = await apolloClient.query({
    query: productsByIdsQuery,
    variables: {
      id: [5, 6, 7, 8]
    }
  }).then((data) => data.data.ProductsByMultipleIds);

  const dataThree = await apolloClient.query({
      query: productsByIdsQuery,
      variables: {
        id: [9, 10, 11, 12]
      }
    }).then((data) => data.data.ProductsByMultipleIds);

  return {
    props: {
      dataOne,
      dataTwo,
      dataThree,
    }
  }
}

interface IFrontPageItem{
  productId: number,
  price: number,
  discountedPrice: number,
  frontImageUrl: string,
  rating: number,
  itemName: string,
  isAvailable: boolean
}

interface IStartProps {
  dataOne: IFrontPageItem[],
  dataTwo: IFrontPageItem[],
  dataThree: IFrontPageItem[]
}

const Home: React.FC<IStartProps> = ({dataOne, dataTwo, dataThree}) => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <MainPageContainer>
          <MainPageBannerComponent></MainPageBannerComponent>
          <ItemsCarouselComponent  dataOne={dataOne} dataTwo={dataTwo} dataThree={dataThree} title={"Trending now"} />
          <BannerText>
            <h1>
              Join our mission to save and protect our buzzy pollinators around the globe❤️
            </h1>
            <p>
              Wear your lovely Bee Kind accessories as a reminder of being part of the community. Every purchase saves the bees.
            </p>
          </BannerText>
          <ItemsCarouselComponent  dataOne={dataOne} dataTwo={dataTwo} dataThree={dataThree} title={"New Arrivals"} />
          <ImageContainer>
            <Image src="https://cdn.shopify.com/s/files/1/0457/5648/1703/files/BEE-ing_Kind_is_a_Lifestyle_2048x.jpg?v=1623903758"
              alt="banner-image" layout={"fill"} objectFit="cover" />
          </ImageContainer>
          <ItemsByCollectionOrStyleComponent isStyle={false}/>
          <EmailInputComponent mainColor={"gray"} title={"Subscribe for exclusive deals"}/>
          <ItemsByCollectionOrStyleComponent isStyle={true}/>
          <ImageContainer>
            <Image src="https://cdn.shopify.com/s/files/1/0457/5648/1703/files/Join_the_Movement_to_Save_Our_Buzzing_Friends_39a722de-5768-4689-84f6-6393f7c5088d_1728x.jpg?v=1623903777"
              alt="banner-image" layout={"fill"} objectFit="cover" />
          </ImageContainer>
        </MainPageContainer>
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
